name: Bump version
on:
  pull_request:
jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
    - uses: fish-shop/install-fish-shell@v1
    - name: Bump version
      run: fish ops/bump-version.fish || true
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: bump version"
